let nouns = [
    'robot',
    'clock',
    'book',
    'laptop',
    'calendar',
    'elevator',
    'escalator',
    'area',
    'business',
    'suitcase',
    'company',
    'home',
    'job',
    'program',
    'app',
    'web app',
    'mobile app',
    'room',
    'course',
    'airplane',
    'bathroom',
    'sport',
    'camp',
    'coin',
    'drawer',
    'eraser',
    'ruler',
    'flag',
    'fork',
    'furniture',
    'handbag',
    'monitor',
    'passport',
    'restaurant',
    'toy',
    'tower',
    'toothpaste',
    'vehicle',
    'pair of glasses',
    'vending machine',
    'water bottle',
];

let users = [
    'computer science students',
    'students',
    'teachers',
    'the old',
    'families',
    'children',
    'blind people',
    'people with disabilities',
    'dancers',
]
export { nouns, users };
